spring:
  application:
    name: ordering-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/vdamov4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa123456
  data:
    redis:
      host: 127.0.0.1
      port: 6378
      password: redis_yawHRX
      database: 0
      timeout: 5s
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

server:
  port: 7081

management:
  endpoints:
    web:
      exposure:
        include: health,info
